name: Integration Test

on:
  pull_request:
    branches:
      - main
      - release-*

  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch name
        id: get_branch
        run: |
          BRANCH=""
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH=${{ github.ref_name }}
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH=${{ github.base_ref }}
          fi
          echo "Branch name: $BRANCH"
          echo "BRANCH=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run helm unittest
        run: make helm-unittest

      - name: Run chart-testing (list-changed)
        id: list-changed
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
        run: |
          changed=$(ct list-changed --target-branch $BRANCH)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
        run: ct lint --check-version-increment=false --target-branch $BRANCH

      - name: Produce the helm documentation
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          make helm-docs
          if ! git diff --quiet -- charts/spark-history-server/README.md; then
            echo "Need to re-run 'make helm-docs' and commit the changes."
            false
          fi
